/**:
  ros__parameters:
    length_in_x: 30.0
    length_in_y: 30.0
    position_x: 0.0
    position_y: 0.0
    resolution: 0.1
    min_variance: 0.00001
    max_variance: 1000.0
    mahalanobis_distance_threshold: 2.5
    multi_height_noise: 0.05
